version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3002:3000'
    env_file:
      - stack.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    depends_on:
      - db
    networks:
      - dimino-network

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dimino
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dimino-network

networks:
  dimino-network:
    driver: bridge

volumes:
  postgres_data:
